export const masrafSeedData = {
  user: {
    name: "أحمد الشمري",
    business: "شمري للتصميم",
    balance: 12840.5,
    currency: "USD",
    country: "JO",
  },
  stats: {
    totalIncome: 18500,
    totalExpenses: 5660,
    pending: 4200,
    overdue: 1800,
  },
  clients: [
    { name: "شركة النجوم", initials: "نج", totalInvoiced: 14200, totalPaid: 9400, overdue: 4800, avgDays: 48, risk: "high", riskScore: 8.2, invoicesCount: 7 },
    { name: "مؤسسة الأفق", initials: "أف", totalInvoiced: 8600, totalPaid: 8600, overdue: 0, avgDays: 12, risk: "low", riskScore: 2.1, invoicesCount: 5 },
    { name: "تقنية المستقبل", initials: "تق", totalInvoiced: 6400, totalPaid: 6400, overdue: 0, avgDays: 18, risk: "low", riskScore: 1.8, invoicesCount: 3 },
    { name: "مجموعة الخليج", initials: "خل", totalInvoiced: 3200, totalPaid: 2200, overdue: 1000, avgDays: 35, risk: "medium", riskScore: 5.4, invoicesCount: 4 },
    { name: "دار الإبداع", initials: "إب", totalInvoiced: 5800, totalPaid: 5800, overdue: 0, avgDays: 9, risk: "low", riskScore: 1.2, invoicesCount: 6 },
    { name: "شركة رياح", initials: "رح", totalInvoiced: 2400, totalPaid: 1200, overdue: 1200, avgDays: 55, risk: "high", riskScore: 7.8, invoicesCount: 2 },
  ],
  invoices: [
    { invoiceNumber: "INV-2026-018", clientName: "شركة النجوم", title: "خدمات تصميم وهوية بصرية", amount: 2400, status: "overdue", dueDate: "2026-04-05", issueDate: "2026-03-05", daysOverdue: 22 },
    { invoiceNumber: "INV-2026-019", clientName: "مؤسسة الأفق", title: "خدمات استشارية رقمية", amount: 1800, status: "sent", dueDate: "2026-04-30", issueDate: "2026-04-01", daysOverdue: 0 },
    { invoiceNumber: "INV-2026-020", clientName: "تقنية المستقبل", title: "تطوير واجهات ومنصات رقمية", amount: 3200, status: "paid", dueDate: "2026-04-12", issueDate: "2026-04-01", daysOverdue: 0 },
    { invoiceNumber: "INV-2026-021", clientName: "مجموعة الخليج", title: "مشروع هوية تجارية", amount: 950, status: "draft", dueDate: null, issueDate: "2026-04-20", daysOverdue: 0 },
    { invoiceNumber: "INV-2026-022", clientName: "دار الإبداع", title: "خدمات إنتاج محتوى", amount: 1450, status: "paid", dueDate: "2026-04-08", issueDate: "2026-03-08", daysOverdue: 0 },
    { invoiceNumber: "INV-2026-023", clientName: "شركة رياح", title: "استكمال مشروع واجهات المستخدم", amount: 600, status: "overdue", dueDate: "2026-04-10", issueDate: "2026-03-10", daysOverdue: 17 },
  ],
  transactions: [
    { type: "income", amount: 3200, date: "2026-04-29", category: null, description: "دفعة من تقنية المستقبل", descriptionAr: "دفعة من تقنية المستقبل", merchantName: "تقنية المستقبل" },
    { type: "expense", amount: -54, date: "2026-04-28", category: "software_tools", description: "Adobe Creative Cloud", descriptionAr: "Adobe Creative Cloud", merchantName: "Adobe" },
    { type: "expense", amount: -29, date: "2026-04-25", category: "software_tools", description: "استضافة الخادم", descriptionAr: "استضافة الخادم", merchantName: "Hosting" },
    { type: "income", amount: 1450, date: "2026-04-24", category: null, description: "دفعة من دار الإبداع", descriptionAr: "دفعة من دار الإبداع", merchantName: "دار الإبداع" },
    { type: "expense", amount: -42, date: "2026-04-23", category: "food_dining", description: "مطعم الرياض", descriptionAr: "مطعم الرياض", merchantName: "مطعم الرياض" },
    { type: "expense", amount: -18, date: "2026-04-22", category: "transport", description: "أوبر", descriptionAr: "أوبر", merchantName: "Uber" },
    { type: "expense", amount: -15, date: "2026-04-20", category: "software_tools", description: "Figma Pro", descriptionAr: "Figma Pro", merchantName: "Figma" },
    { type: "income", amount: 800, date: "2026-04-18", category: null, description: "دفعة جزئية من النجوم", descriptionAr: "دفعة جزئية من النجوم", merchantName: "شركة النجوم" },
  ],
  cashflow: [
    { month: "يناير", income: 9200, expenses: 3100 },
    { month: "فبراير", income: 11400, expenses: 4200 },
    { month: "مارس", income: 8700, expenses: 3800 },
    { month: "أبريل", income: 14600, expenses: 5660 },
    { month: "مايو", income: 12200, expenses: 4100 },
    { month: "يونيو", income: 13800, expenses: 4500 },
  ],
  expenseCategories: [
    { name: "برمجيات وأدوات", nameEn: "Software", amount: 98, color: "#1B5E20", pct: 40 },
    { name: "طعام ومطاعم", nameEn: "Food", amount: 42, color: "#C6930A", pct: 17 },
    { name: "مواصلات", nameEn: "Transport", amount: 36, color: "#7B1FA2", pct: 15 },
    { name: "اتصالات", nameEn: "Comms", amount: 28, color: "#0D47A1", pct: 11 },
    { name: "أخرى", nameEn: "Other", amount: 43, color: "#9C9C95", pct: 17 },
  ],
  zakat: {
    totalAssets: 28400,
    nisab: 8400,
    eligible: 12840.5,
    rate: 0.025,
    amount: 321,
    aboveNisab: true,
    daysUntilDue: 38,
    lastPaid: "2025-04-01",
  },
  contracts: [
    { title: "عقد تصميم موقع شركة النجوم", clientName: "شركة النجوم", status: "analyzed", flagsCount: 2, criticalFlags: 1, amount: 4800, date: "2026-04-20" },
    { title: "اتفاقية خدمات تسويقية", clientName: "مجموعة الخليج", status: "analyzed", flagsCount: 0, criticalFlags: 0, amount: 2200, date: "2026-04-12" },
    { title: "عقد تطوير تطبيق", clientName: "تقنية المستقبل", status: "pending", flagsCount: 0, criticalFlags: 0, amount: 9600, date: "2026-04-27" },
  ],
  contractFlags: [
    { severity: "critical", title: "بند تعسفي في إنهاء العقد", desc: "يمنح العميل حق إنهاء العقد دون مدة إشعار مسبق مع احتفاظه بكامل الأعمال المنجزة", clause: "البند ١٢.٣", recommendation: "اطلب تعديل البند ليتضمن إشعاراً مسبقاً لا يقل عن ١٤ يوماً والحصول على نسبة من الأعمال المنجزة" },
    { severity: "warning", title: "غموض في نطاق العمل", desc: "وصف نطاق العمل فضفاض ويسمح للعميل بطلب تعديلات غير محدودة", clause: "البند ٣.١", recommendation: "حدد عدد مراجعات محدود وآلية لتسعير الأعمال الإضافية" },
  ],
  voiceCommands: [
    "كم رصيدي؟",
    "أرسل فاتورة لشركة النجوم بمبلغ ٥٠٠ دولار",
    "ذكّر شركة النجوم بفاتورتها المتأخرة",
    "كم صرفت هذا الشهر؟",
    "احسب زكاتي",
    "خذني للفواتير",
    "مين أسوأ عميل عندي؟",
  ],
} as const;
