import PDFDocument from "pdfkit";
import { existsSync } from "node:fs";
import type { ReportRow } from "../../infrastructure/database/schema.js";

const PAGE_WIDTH = 595.28;
const MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

const MONTHS_AR = [
  "",
  "يناير",
  "فبراير",
  "مارس",
  "أبريل",
  "مايو",
  "يونيو",
  "يوليو",
  "أغسطس",
  "سبتمبر",
  "أكتوبر",
  "نوفمبر",
  "ديسمبر",
];

const MONTHS_EN = [
  "",
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export interface ReportPdfInput {
  report: ReportRow;
}

export async function generateReportPdfBuffer({ report }: ReportPdfInput): Promise<Buffer> {
  return await new Promise<Buffer>((resolve, reject) => {
    const document = new PDFDocument({ size: "A4", margin: MARGIN });
    const chunks: Buffer[] = [];

    document.on("data", (chunk: Buffer) => chunks.push(chunk));
    document.on("end", () => resolve(Buffer.concat(chunks)));
    document.on("error", reject);

    const font = setupFonts(document);
    document.font(font);

    document.rect(0, 0, PAGE_WIDTH, 104).fill("#0f172a");
    document.fillColor("#ffffff").fontSize(23).text("Financial Report", MARGIN, 28, {
      width: 240,
    });
    document.fontSize(23).text("تقرير مالي", 315, 28, {
      width: 230,
      align: "right",
      features: ["liga", "rlig", "calt"],
    });
    document.fontSize(10).fillColor("#cbd5e1").text(
      `${MONTHS_EN[report.periodMonth]} ${report.periodYear} | ${MONTHS_AR[report.periodMonth]} ${report.periodYear}`,
      MARGIN,
      66,
      { width: CONTENT_WIDTH, align: "center", features: ["liga", "rlig", "calt"] },
    );

    addMetric(document, "Income", "الدخل", report.totalIncome, 132, "#059669");
    addMetric(document, "Expenses", "المصروفات", report.totalExpenses, 132, "#dc2626", 1);
    addMetric(document, "Net Profit", "صافي الربح", report.netProfit, 252, "#2563eb");

    addCount(document, "Invoices sent", "الفواتير المرسلة", report.invoicesSent, 390);
    addCount(document, "Invoices paid", "الفواتير المدفوعة", report.invoicesPaid, 430);
    addCount(document, "Invoices overdue", "الفواتير المتأخرة", report.invoicesOverdue, 470);

    document.moveTo(MARGIN, 535).lineTo(MARGIN + CONTENT_WIDTH, 535).strokeColor("#e2e8f0").stroke();
    document.fontSize(14).fillColor("#0f172a").text("AI Summary", MARGIN, 560, {
      width: 220,
    });
    document.fontSize(14).text("ملخص الذكاء الاصطناعي", 315, 560, {
      width: 230,
      align: "right",
      features: ["liga", "rlig", "calt"],
    });

    document.fontSize(10).fillColor("#334155").text(report.aiSummary ?? "No English summary available.", MARGIN, 595, {
      width: 225,
      lineGap: 4,
    });
    document.fontSize(10).fillColor("#334155").text(report.aiSummaryAr ?? "لا يوجد ملخص عربي.", 315, 595, {
      width: 230,
      align: "right",
      lineGap: 4,
      features: ["liga", "rlig", "calt"],
    });

    document.fontSize(9).fillColor("#64748b").text("Generated by Masraf", MARGIN, 800, {
      width: CONTENT_WIDTH,
      align: "center",
    });

    document.end();
  });
}

function setupFonts(document: PDFKit.PDFDocument): string {
  const fontPath = [
    process.env.MASRAF_PDF_FONT_PATH,
    "C:/Windows/Fonts/arial.ttf",
    "C:/Windows/Fonts/tahoma.ttf",
    "/usr/share/fonts/truetype/noto/NotoSansArabic-Regular.ttf",
    "/usr/share/fonts/opentype/noto/NotoNaskhArabic-Regular.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
  ].filter(Boolean).find((path) => existsSync(path as string));

  if (!fontPath) {
    return "Helvetica";
  }

  document.registerFont("MasrafReportRegular", fontPath as string);
  return "MasrafReportRegular";
}

function addMetric(
  document: PDFKit.PDFDocument,
  labelEn: string,
  labelAr: string,
  value: string,
  y: number,
  color: string,
  column = 0,
) {
  const x = column === 0 ? MARGIN : 315;
  const width = column === 0 ? 230 : 230;

  document.roundedRect(x, y, width, 88, 8).fill("#f8fafc").stroke("#e2e8f0");
  document.fontSize(10).fillColor("#64748b").text(labelEn, x + 16, y + 16, {
    width: width - 32,
  });
  document.fontSize(10).fillColor("#64748b").text(labelAr, x + 16, y + 16, {
    width: width - 32,
    align: "right",
    features: ["liga", "rlig", "calt"],
  });
  document.fontSize(20).fillColor(color).text(Number(value).toFixed(2), x + 16, y + 44, {
    width: width - 32,
    align: "right",
  });
}

function addCount(
  document: PDFKit.PDFDocument,
  labelEn: string,
  labelAr: string,
  value: number,
  y: number,
) {
  document.fontSize(11).fillColor("#334155").text(labelEn, MARGIN, y, { width: 190 });
  document.fontSize(11).fillColor("#334155").text(labelAr, 245, y, {
    width: 190,
    align: "right",
    features: ["liga", "rlig", "calt"],
  });
  document.fontSize(12).fillColor("#0f172a").text(String(value), 465, y, {
    width: 80,
    align: "right",
  });
}
