import swaggerJsdoc from "swagger-jsdoc";

const port = process.env.PORT || 4000;
const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Masraf API — مصرف",
      version: "1.0.0",
      description:
        "The AI Financial Co-Pilot for Arab Freelancers | المستشار المالي الذكي للمستقلين العرب",
      contact: {
        name: "Masraf Team",
        url: "https://masraf.app",
      },
    },
    servers: [
      {
        url: `http://localhost:${port}`,
        description: "Development server",
      },
      {
        url: "https://api.masraf.app",
        description: "Production server",
      },
    ],
    components: {
      schemas: {
        // ── Enums ──
        InvoiceStatus: {
          type: "string",
          enum: ["draft", "sent", "viewed", "paid", "overdue", "cancelled"],
          description: "Invoice status",
        },
        PaymentTerms: {
          type: "string",
          enum: [
            "immediate",
            "net_7",
            "net_15",
            "net_30",
            "net_60",
            "murabaha",
            "musharakah",
          ],
          description: "Islamic payment terms",
        },
        ExpenseCategory: {
          type: "string",
          enum: [
            "food_dining",
            "transport",
            "software_tools",
            "office_supplies",
            "communication",
            "marketing",
            "education",
            "health",
            "rent",
            "utilities",
            "entertainment",
            "other",
          ],
          description: "Expense category",
        },
        RiskLevel: {
          type: "string",
          enum: ["low", "medium", "high"],
          description: "Client risk level",
        },
        FlagSeverity: {
          type: "string",
          enum: ["info", "warning", "critical"],
          description: "Contract flag severity",
        },
        TransactionType: {
          type: "string",
          enum: ["income", "expense"],
          description: "Transaction type",
        },
        AnalysisStatus: {
          type: "string",
          enum: ["pending", "analyzing", "completed", "failed"],
          description: "Contract analysis status",
        },
        VoicePersona: {
          type: "string",
          enum: ["abdullah", "sha"],
          description: "TTS voice persona",
        },

        // ── Models ──
        Client: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            name: { type: "string" },
            nameAr: { type: "string" },
            email: { type: "string", format: "email" },
            phone: { type: "string" },
            company: { type: "string" },
            companyAr: { type: "string" },
            notes: { type: "string" },
            riskLevel: { $ref: "#/components/schemas/RiskLevel" },
            riskScore: { type: "number", minimum: 0, maximum: 10 },
            totalInvoiced: { type: "number" },
            totalPaid: { type: "number" },
            totalOverdue: { type: "number" },
            avgPaymentDays: { type: "integer" },
            invoicesCount: { type: "integer" },
            latePaymentsCount: { type: "integer" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
          required: ["id", "name", "riskLevel", "riskScore", "createdAt"],
        },

        Invoice: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            clientId: { type: "string", format: "uuid" },
            invoiceNumber: { type: "string", description: "INV-YYYY-XXX" },
            title: { type: "string" },
            titleAr: { type: "string" },
            subtotal: { type: "number" },
            vatAmount: { type: "number" },
            total: { type: "number" },
            currency: { type: "string", default: "USD" },
            paymentTerms: { $ref: "#/components/schemas/PaymentTerms" },
            issueDate: { type: "string", format: "date" },
            dueDate: { type: "string", format: "date" },
            status: { $ref: "#/components/schemas/InvoiceStatus" },
            paidAt: { type: "string", format: "date-time" },
            viewedAt: { type: "string", format: "date-time" },
            sentAt: { type: "string", format: "date-time" },
            murabahaTerms: { type: "string" },
            profitRate: { type: "number" },
            pdfUrl: { type: "string", format: "uri" },
            generatedByVoice: { type: "boolean" },
            chaserSent: { type: "boolean" },
            chaserMessage: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
          required: ["id", "invoiceNumber", "title", "subtotal", "total", "status", "createdAt"],
        },

        InvoiceItem: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            invoiceId: { type: "string", format: "uuid" },
            description: { type: "string" },
            descriptionAr: { type: "string" },
            quantity: { type: "number" },
            unitPrice: { type: "number" },
            total: { type: "number" },
            sortOrder: { type: "integer" },
          },
          required: ["id", "invoiceId", "description", "unitPrice", "total"],
        },

        Transaction: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            type: { $ref: "#/components/schemas/TransactionType" },
            amount: { type: "number" },
            currency: { type: "string", default: "USD" },
            category: { $ref: "#/components/schemas/ExpenseCategory" },
            description: { type: "string" },
            descriptionAr: { type: "string" },
            merchantName: { type: "string" },
            reference: { type: "string" },
            transactionDate: { type: "string", format: "date" },
            isHalal: { type: "boolean", default: true },
            needsPurification: { type: "boolean", default: false },
            createdAt: { type: "string", format: "date-time" },
          },
          required: ["id", "type", "amount", "transactionDate", "createdAt"],
        },

        Contract: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            clientId: { type: "string", format: "uuid" },
            title: { type: "string" },
            titleAr: { type: "string" },
            filePath: { type: "string" },
            fileUrl: { type: "string", format: "uri" },
            fileSize: { type: "integer" },
            originalFilename: { type: "string" },
            analysisStatus: { $ref: "#/components/schemas/AnalysisStatus" },
            analysisResult: { type: "object" },
            keyTerms: { type: "object" },
            paymentAmount: { type: "number" },
            paymentSchedule: { type: "string" },
            contractDuration: { type: "string" },
            terminationClause: { type: "string" },
            analyzedAt: { type: "string", format: "date-time" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
          required: ["id", "title", "filePath", "analysisStatus", "createdAt"],
        },

        ContractFlag: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            contractId: { type: "string", format: "uuid" },
            severity: { $ref: "#/components/schemas/FlagSeverity" },
            title: { type: "string" },
            titleAr: { type: "string" },
            description: { type: "string" },
            descriptionAr: { type: "string" },
            clauseReference: { type: "string" },
            recommendation: { type: "string" },
            recommendationAr: { type: "string" },
            sortOrder: { type: "integer" },
          },
          required: ["id", "contractId", "severity", "title", "description"],
        },

        ZakatRecord: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            periodStart: { type: "string", format: "date" },
            periodEnd: { type: "string", format: "date" },
            totalIncome: { type: "number" },
            qualifyingAssets: { type: "number" },
            nisabThreshold: { type: "number" },
            aboveNisab: { type: "boolean" },
            zakatRate: { type: "number", default: 0.025 },
            zakatAmount: { type: "number" },
            paid: { type: "boolean", default: false },
            paidAt: { type: "string", format: "date-time" },
            currency: { type: "string", default: "USD" },
            calculationDetails: { type: "object" },
            createdAt: { type: "string", format: "date-time" },
          },
          required: [
            "id",
            "periodStart",
            "periodEnd",
            "totalIncome",
            "qualifyingAssets",
            "zakatAmount",
            "createdAt",
          ],
        },

        VoiceLog: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            transcript: { type: "string" },
            intent: { type: "string" },
            actionTaken: { type: "string" },
            responseText: { type: "string" },
            sourcePage: { type: "string" },
            navigatedTo: { type: "string" },
            voiceUsed: { $ref: "#/components/schemas/VoicePersona" },
            processingTimeMs: { type: "integer" },
            success: { type: "boolean", default: true },
            createdAt: { type: "string", format: "date-time" },
          },
          required: ["id", "createdAt"],
        },

        Report: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            periodMonth: { type: "integer", minimum: 1, maximum: 12 },
            periodYear: { type: "integer" },
            totalIncome: { type: "number" },
            totalExpenses: { type: "number" },
            netProfit: { type: "number" },
            invoicesSent: { type: "integer" },
            invoicesPaid: { type: "integer" },
            invoicesOverdue: { type: "integer" },
            topClientId: { type: "string", format: "uuid" },
            topCategory: { $ref: "#/components/schemas/ExpenseCategory" },
            aiSummary: { type: "string" },
            aiSummaryAr: { type: "string" },
            pdfPath: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
          },
          required: ["id", "periodMonth", "periodYear", "createdAt"],
        },

        ApiResponse: {
          type: "object",
          properties: {
            success: { type: "boolean" },
            message: { type: "string" },
            data: { type: "object" },
          },
        },

        Error: {
          type: "object",
          properties: {
            success: { type: "boolean", default: false },
            message: { type: "string" },
            code: { type: "string" },
          },
        },
      },
    },
    tags: [
      { name: "Health", description: "Health check endpoints" },
      { name: "Clients", description: "Client management" },
      { name: "Invoices", description: "Invoice management" },
      { name: "Transactions", description: "Transaction records" },
      { name: "Contracts", description: "Contract management & analysis" },
      { name: "Zakat", description: "Zakat calculation & tracking" },
      { name: "Reports", description: "Financial reports" },
      { name: "AI", description: "AI-powered features" },
      { name: "Voice", description: "Voice interface" },
    ],
  },
  apis: ["./src/modules/**/*.routes.ts", "./src/app.ts"],
};

export const swaggerSpec = swaggerJsdoc(options);
